### ISSUE TITLE
Error in the about section

### ISSUE THREAD

**Issue by Khobalt** [TBD54566975/collaboration#41]
`"Collaboration" - a word we made up which combines "Collaboration" and "Innovation". `

This wasn't intended, right?

**Comment by Khobalt** [comment]
![image](https://user-images.githubusercontent.com/848683/189952773-318b6e8f-5f11-4f24-89c2-e9ade416eb22.png)

**Comment by ALRubinger** [comment]
It was intended, because at TBD we've a zany sense of humor. :P

Updating description in the name of clarity; I agree :)
