### ISSUE TITLE
Getting started link is dead

### ISSUE THREAD

**Issue by kimdhamilton** [TBD54566975/collaboration#50]
`GETTING_STARTED_DWP.md` doesn't exist. It was renamed to `GETTING_STARTED_WEB5.md` in this commit https://github.com/TBD54566975/collaboration/commit/10197b309ed6c22fe376f86285fe25a32a8bef87, but given the context of the sentence I'm not sure whether you want to update the link or sentence too.

> Building tbDEX as a specification and message format is work that will follow the foundational projects under active development with the [Decentralized Web Platform (DWP)](https://github.com/TBD54566975/collaboration/blob/main/projects/GETTING_STARTED_DWP.md).

**Comment by ALRubinger** [comment]
Thank you, @kimdhamilton! Doing cleanup on this repo as we've moved authoritative Getting Started to https://developer.tbd.website/open-source/contributing
