### ISSUE TITLE
Contribution Pages: Remove Forums

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/collaboration#55]
Pages that need to be updated:

SSI Service - https://github.com/TBD54566975/ssi-service/blob/main/CONTRIBUTING.md
SSI SDK - https://github.com/TBD54566975/ssi-sdk/blob/main/CONTRIBUTING.md
Web5 JS - https://github.com/TBD54566975/web5-js/blob/main/CONTRIBUTING.md

**Comment by ALRubinger** [comment]
Awesome ty!

**Comment by bobbilee19** [comment]
I updated all three!

**Comment by ALRubinger** [comment]
DNS records changes are now underway with @tlongwell-block, dependency of getting this issue for forums done.

**Comment by ALRubinger** [comment]
Confirmed done for the 3 pages referenced in the description; cleaning up
